[package]
name = "trunk-template"
version = "0.1.0"
edition = "2021"
description = "Template for starting a Yew project using Trunk"
readme = "README.md"
# repository = "https://github.com/yewstack/yew-trunk-minimal-template"
# license = "MIT OR Apache-2.0"
# keywords = ["yew", "trunk"]
# categories = ["gui", "wasm", "web-programming"]
[lib]
crate-type = ["cdylib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { version = "0.21", features = ["csr"] }
serde-wasm-bindgen = "0.5.0"
wasm-bindgen = "0.2.78"
web-sys = "0.3.64"
gloo = "0.9.0"
js-sys = "0.3.64"
stylist = { version = "0.13.0", features = ["yew_integration"] }
